import { StyleSheet, Platform, StatusBar, Dimensions } from "react-native";

export default StyleSheet.create({
    AndriodSafeArea: {
        flex: 1,
        backgroundColor: "#201A2E",
        paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
    },
    homeContainer: {
        padding: 20,
        paddingTop: 40,
        backgroundColor: "#201A2E",
        flex: 1,
        height: Dimensions.get("screen").height,
        position: "relative",
        fontFamily: "RHD_400",
    },

    title: {
        color: "white",
        marginTop: 20,
        fontSize: 24,
        paddingRight: "10%",
        fontFamily: "RHD_700",
    },
    subtitle: {
        color: "#797682",
        fontSize: 12,
        marginTop: 20,
        paddingRight: 50,
    },
    strategiesContainer: {
        marginTop: 0,
    },
    strgyCardContainer: {
        padding: 15,
        backgroundColor: "#7976821c",
        borderRadius: 15,
        borderWidth: 1,
        borderColor: "#797682",
        minHeight: 200,
        marginTop: 35,
        paddingBottom: 40,
    },
    rowSpaceBtn: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginTop: 20,
    },
    cardTitle: {
        color: "white",
        fontWeight: "700",
        marginTop: 10,
        fontSize: 20,
    },
    titleGreen: {
        fontWeight: "700",
        marginTop: 10,
        color: "#99CF84",
        fontSize: 20,
    },
    title20: {
        color: "white",
        fontWeight: "600",
        fontSize: 20,
    },
    subTitle: {
        color: "#797682",
    },
    subTitle2: {
        color: "#A9A9A9",
        marginTop: 10,
        width: "85%",
    },
    faqSubtitle: {
        color: "#827F8A",
        fontSize: 12,
        width: "90%",
    },
    profileActionsContainer: {
        position: "absolute",
        bottom: "10%",
        left: 20,
    },
    btnPosition: {
        marginTop: 40,
    },
    btnsContainer: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        width: "100%",
    },

    rowCenter: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
    },

    rowVerticalAlign: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
    },
    transBtn: {
        width: "48%",
        height: 57,
        display: "flex",
        justifyContent: "center",
    },
    transBtnContent: {
        borderColor: "white",
        borderRadius: 15,
        borderWidth: 1,
        borderColor: "#797682",
    },
    stepGradBtn: {
        width: "48%",
    },
    faqTitlePink: {
        color: "#A528DD",
        fontWeight: "500",
    },
    divider: {
        backgroundColor: "white",
        marginTop: 10,
    },
    accordionContainer: {
        color: "white",
        padding: 0,
        margin: 0,
    },
    inviteVector: {
        paddingRight: 40,
    },
    investBtn: {
        width: "100%",
        marginTop: 20,
        borderRadius: 12,
        height: 58,
        display: "flex",
        justifyContent: "center",
        borderColor: "white",
    },
    referalContainer: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        marginTop: 30,
    },
    portfolioCard: {
        padding: 15,
        backgroundColor: "#ffffff0d",
        borderStyle: "solid",
        borderColor: "#797682",
        borderWidth: 1,
        paddingBottom: 30,
        marginTop: 40,
        position: "relative",
        borderRadius: 15,
        minHeight: 250,
    },
    portfolioText1: {
        marginLeft: 30,
        fontSize: 18,
        color: "white",
        fontWeight: "700",
    },
    pfColumnContainer: {
        display: "flex",
        justifyContent: "center",
        marginTop: 30,
    },
    pfRowContainer: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    divider: {
        backgroundColor: "white",
        marginTop: 25,
    },
    cardFooter: {
        marginTop: 5,
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    safetyScore: {
        width: "35%",
    },
    howItWorks: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
    },
    amountDispContainer: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: 30,
        width: "100%",
    },
    amtDisplay: {
        backgroundColor: "#A528DD",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        width: 320,
        padding: 20,
        borderRadius: 13,
    },
    descTxt: {
        color: "white",
        fontSize: 16,
        marginBottom: 15,
    },
    amountTxt: {
        color: "white",
        fontSize: 40,
        fontFamily: "RHD_700",
        marginBottom: 15,
    },
    usdtTxt: {
        color: "white",
        opacity: 0.3,
        fontSize: 16,
    },
    sliderContainer: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
    },
    bankPreviewCard: {
        display: "flex",
        flexDirection: "row",
        borderColor: "#797682",
        borderWidth: 1,
        minHeight: 114,
        marginTop: 100,
        padding: 10,
        position: "relative",
    },
    radioButton: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 50,
        width: 25,
        height: 25,
        borderColor: "#A528DD",
        borderWidth: 1,
        marginRight: 15,
    },
    radioFilled: {
        width: 15,
        height: 15,
        borderRadius: 50,
        backgroundColor: "#55ADFF",
    },
    PaymentCardContainer: {
        padding: 15,
        paddingBottom: 30,
        paddingTop: 30,
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#ffffff0f",
        borderWidth: 1,
        borderColor: "#797682",
        marginTop: 20,
    },
    riveraBankDetailsContainer: {
        padding: 15,
        backgroundColor: "#ffffff0f",
        borderWidth: 1,
        borderColor: "#797682",
        marginTop: 20,
        paddingBottom: 30,
        paddingTop: 30,
    },
    iconsContainer: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
    },
    iconParent: {
        backgroundColor: "#4A4556",
        borderRadius: 50,
        width: 55,
        height: 55,
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        marginRight: 20,
    },
    ctaContainer: {
        width: "100%",
        display: "flex",
        alignItems: "flex-end",
        position: "absolute",
        bottom: "-30%",
    },
    vectorContainer: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        marginTop: 20,
    },
    inputContainer: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        marginTop: 40,
        width: "90%",
        position: "relative",
    },
    inputTypeStyle: {
        backgroundColor: "#201A2E",
        color: "white",
        fontSize: 20,
        fontWeight: "600",
        letterSpacing: 2,
        width: "100%",
        height: 350,
    },

    inputContainer: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 40,
        width: '90%',
        position: 'relative',
    },
    inputTypeStyle: {
        backgroundColor: '#201A2E',
        color: 'white',
        fontSize: 26,
        fontFamily: 'RHD_600',
        letterSpacing: 2,
        width: '100%',
    },
    ctaContainer: {
        width: '100%',
        display: 'flex',
        alignItems: 'flex-end',
        marginTop: 50,
    },
    otpDetailsContainer: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 40,
    },
    subtitle: {
        color: '#797682',
        fontSize: 16,
    },
    subtitle2: {
        color: '#7479F1',
        fontSize: 16,
        marginLeft: 10,
    },
    resendOtpContainer: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 40,
    },
    otpSubTitle: {
        color: '#797682',
        fontSize: 16,
    },
    otpSubTitle2: {
        color: '#7479F1',
        fontSize: 16,
        marginLeft: 10,
    },
    errorText: {
        color: '#FF3333',
        marginTop: 10,
        fontSize: 15,
        position: 'absolute',
        top: 30,
    },
    WithdrawSummaryAmoutCont: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: "#797682",
        marginTop: 40,
        padding: 20,
        minHeight: 170
    },
    introDisplay: {
        width: '45%',
        height: 98,
        borderRadius: 20,
        marginTop: 60,
        padding: 20
    },
    tabsContainer: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 40,
        marginBottom: 20
    },
    tabContainer: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        width: '48%',
        minHeight: 50,
        borderRadius: 12,
    },
    activeTab: {
        backgroundColor: 'white',
        color: 'black'
    },
    transactionsView: {
        marginTop: 20
    },
    transactionCard: {
        padding: 20,
        marginTop: 13,
        backgroundColor: '#2D283A',
        borderRadius: 10,
        minHeight: 130,
        width: '100%',
        display: 'flex',
        flexDirection: 'row'
    },
    iconContainer: {
        width: 32,
        height: 32,
        borderRadius: 50,
        padding: 5,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        backgroundColor: '#ffffff29',
        
    },
    contentContainer: {
        width: '86%',
        marginLeft: 10
    }
});
